/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cst242.finalproject.client.viewcontroller;

import java.awt.Component;
import javax.swing.JButton;

/**
 *
 * @author James DeCarlo
 */
public class PrimaryPanel extends javax.swing.JPanel {

    /**
     * Creates new form PrimaryPanel
     */
    public PrimaryPanel() {
        initComponents();
    }

    public JButton getBtnExit() {
        return btnExit;
    }

    public JButton getBtnLogin() {
        return btnLogin;
    }

    public JButton getBtnRegister() {
        return btnRegister;
    }    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLogin = new javax.swing.JButton();
        btnRegister = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        btnLogin.setText("Login");
        btnLogin.setToolTipText("Click to login");
        btnLogin.setActionCommand("primaryLogin");
        btnLogin.setAlignmentX(Component.CENTER_ALIGNMENT);

        btnRegister.setText("Register");
        btnRegister.setToolTipText("Click to register");
        btnRegister.setActionCommand("primaryRegister");
        btnRegister.setAlignmentX(Component.CENTER_ALIGNMENT);

        btnExit.setText("Exit");
        btnExit.setToolTipText("Click to exit");
        btnExit.setActionCommand("primaryExit");
        btnExit.setAlignmentX(Component.CENTER_ALIGNMENT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(btnLogin))
                    .addComponent(btnRegister)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btnExit)))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(btnLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRegister)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExit))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnRegister;
    // End of variables declaration//GEN-END:variables
}
