package com.cst242.finalproject.client.viewcontroller;

import javax.swing.JButton;
import javax.swing.JList;

/**
 * This class is for the select rooms form panel.
 * 
 * @author James DeCarlo
 */
public class SelectRoomsPanel extends javax.swing.JPanel {

    /**
     * Creates new form SelectRoomsPanel
     */
    public SelectRoomsPanel() {
        initComponents();
    }

    /**
     * Gets the cancel button.
     * @return The cancel button.
     */
    public JButton getBtnCancel() {
        return btnCancel;
    }

    /**
     * Gets the create new room button.
     * @return The create new room button.
     */
    public JButton getBtnCreateNewRoom() {
        return btnCreateNewRoom;
    }

    /**
     * Gets the enter button.
     * @return The enter button.
     */
    public JButton getBtnEnter() {
        return btnEnter;
    }

    /**
     * Gets the select room list.
     * @return The select room list.
     */
    public JList getLstSelectRoom() {
        return lstSelectRoom;
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstSelectRoom = new javax.swing.JList();
        btnEnter = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnCreateNewRoom = new javax.swing.JButton();

        lstSelectRoom.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), "Select Room"));
        lstSelectRoom.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(lstSelectRoom);

        btnEnter.setText("Enter");
        btnEnter.setToolTipText("Click to start chatting");
        btnEnter.setActionCommand("selectRoomsEnter");

        btnCancel.setText("Cancel");
        btnCancel.setToolTipText("Click to cancel");
        btnCancel.setActionCommand("selectRoomsCancel");

        btnCreateNewRoom.setText("Create New Room");
        btnCreateNewRoom.setToolTipText("Click to create new room");
        btnCreateNewRoom.setActionCommand("selectRoomsCreateNewRoom");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnEnter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnCreateNewRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEnter)
                    .addComponent(btnCancel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCreateNewRoom)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnCreateNewRoom;
    private javax.swing.JButton btnEnter;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList lstSelectRoom;
    // End of variables declaration//GEN-END:variables
}
